name: Release version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
# This job will build the binary and make it available for further jobs.
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1 

    - name: Build
      run: go build -o reterm

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: reterm
        path: ./reterm

# This job will release the version
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1 

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: reterm
        path: ./

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./reterm
        asset_name: reterm
        asset_content_type: application/octet-stream
