name: Release version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # This job will build the binary and make it available for further jobs.
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1 

    - name: Build
      run: go build -o reterm

    - name: Create Tarball Archive
      run: |
        tar -czvf reterm.tar.gz reterm
      working-directory: ${{ github.workspace }}

    - name: Create Linux AMD64 Tarball Archive
      run: |
        GOARCH=amd64 GOOS=linux go build -o reterm-linux-amd64 reterm
        tar -czvf reterm-linux-amd64.tar.gz reterm-linux-amd64
      working-directory: ${{ github.workspace }}

    - name: List Tarball Archive Paths
      run: |
        echo "reterm.tar.gz is located at: ${{ github.workspace }}/reterm.tar.gz"
        echo "reterm-linux-amd64.tar.gz is located at: ${{ github.workspace }}/reterm-linux-amd64.tar.gz"

    - name: Upload Tarball Archives
      uses: actions/upload-artifact@v2
      with:
        name: reterm
        path: |
          ./reterm.tar.gz
          ./reterm-linux-amd64.tar.gz

  # This job will release the version
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1 

    - name: Extract Tag Name
      id: extract_tag
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: List Files
      run: ls -R

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.extract_tag.outputs.tag }}
        release_name: Release ${{ steps.extract_tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      id: upload-release-assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          ${{ github.workspace }}/reterm.tar.gz
          ${{ github.workspace }}/reterm-linux-amd64/reterm-linux-amd64.tar.gz
        asset_name: |
          reterm-${{ steps.extract_tag.outputs.tag }}.src.tar.gz
          reterm-${{ steps.extract_tag.outputs.tag }}-linux-amd64.tar.gz
        asset_content_type: |
          application/gzip
          application/gzip
