name: Release version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  # This job will build the binary and make it available for further jobs.
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1 

    - name: Build
      run: go build -o reterm

    - name: Create Tarball Archive
      run: |
        tar -czvf reterm.tar.gz reterm
      working-directory: ${{ github.workspace }}

    - name: Upload Tarball Archive
      uses: actions/upload-artifact@v2
      with:
        name: reterm
        path: ./reterm.tar.gz

  # This job will release the version
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.1 

    - name: Download Tarball Archive
      uses: actions/download-artifact@v2
      with:
        name: reterm
        path: ./

    - name: Extract Tag Name
      id: extract_tag
      run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.extract_tag.outputs.tag }}
        release_name: Release ${{ steps.extract_tag.outputs.tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./reterm.tar.gz
        asset_name: traefik-${{ steps.extract_tag.outputs.tag }}.src.tar.gz
        asset_content_type: application/gzip
